name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  quick-build:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare git
        run:
          git config --global url."git://github.com/ghc/packages-".insteadOf     git://github.com/ghc/packages/ &&
          git config --global url."http://github.com/ghc/packages-".insteadOf    http://github.com/ghc/packages/ &&
          git config --global url."https://github.com/ghc/packages-".insteadOf   https://github.com/ghc/packages/ &&
          git config --global url."ssh://git@github.com/ghc/packages-".insteadOf ssh://git@github.com/ghc/packages/ &&
          git config --global url."git@github.com:ghc/packages-".insteadOf       git@github.com:ghc/packages/

      - name: Checkout GHC
        uses: actions/checkout@v2
        with:
          repository: ghc/ghc
          submodules: recursive

      - name: Checkout ghc.nix
        uses: actions/checkout@v2
        with:
          path: ghc.nix

      - name: Install nix
        uses: cachix/install-nix-action@v12

      - name: Use cachix
        uses: cachix/cachix-action@v7
        with:
          name: ghc-nix
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'

      - name: Run nix-shell - Boot and Configure
        run: nix-shell --pure ghc.nix --command "./boot && configure_ghc"

      - name: Run nix-shell - Build Hadrian
        run: nix-shell --pure ghc.nix --command "pushd hadrian; cabal new-update; cabal new-build -j all; popd"

      - name: Run nix-shell - hadrian/ghci
        run: nix-shell --pure ghc.nix --command "echo :q | hadrian/ghci | tail -n2 | grep 'Ok,'"

  all-options-build:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare git
        run:
          git config --global url."git://github.com/ghc/packages-".insteadOf     git://github.com/ghc/packages/ &&
          git config --global url."http://github.com/ghc/packages-".insteadOf    http://github.com/ghc/packages/ &&
          git config --global url."https://github.com/ghc/packages-".insteadOf   https://github.com/ghc/packages/ &&
          git config --global url."ssh://git@github.com/ghc/packages-".insteadOf ssh://git@github.com/ghc/packages/ &&
          git config --global url."git@github.com:ghc/packages-".insteadOf       git@github.com:ghc/packages/

      - name: Checkout GHC
        uses: actions/checkout@v2
        with:
          repository: ghc/ghc
          submodules: recursive

      - name: Checkout ghc.nix
        uses: actions/checkout@v2
        with:
          path: ghc.nix

      - name: Install nix
        uses: cachix/install-nix-action@v12

      - name: Use cachix
        uses: cachix/cachix-action@v7
        with:
          name: ghc-nix
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      
      - name: Create shell.nix with all options
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: ${{ GITHUB_WORKSPACE }}/shell.nix
          contents: |
            import ghc.nix/default.nix {
              withDocs = true;
              withHadrianDeps = true;
              withLlvm = true;
              withIde = true;
            }
          write-mode: overwrite
  
      - name: Run nix-shell - Boot and Configure
        run: nix-shell --pure --command "./boot && configure_ghc"

      - name: Run nix-shell - Build Hadrian
        run: nix-shell --pure --command "pushd hadrian; cabal new-update; cabal new-build -j all; popd"

      - name: Run nix-shell - hadrian/ghci
        run: nix-shell --pure --command "echo :q | hadrian/ghci | tail -n2 | grep 'Ok,'"
